version: '3.8'

services:
  proxy:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy-monk
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fyle-api      
  fyle-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7755:7755"







